#!/usr/bin/env bash

# get scripts Base regardless of execution location
SOURCE="${BASH_SOURCE[0]}"
while [ -h "$SOURCE" ]; do # resolve $SOURCE until the file is no longer a symlink
    DIR="$( cd -P "$( dirname "$SOURCE" )" && pwd )"
    SOURCE="$(readlink "$SOURCE")"
    [[ $SOURCE != /* ]] && SOURCE="$DIR/$SOURCE" # if $SOURCE was a relative symlink, we need to resolve it relative to the path where the symlink file was located
done
scriptsBase="$(dirname "$SOURCE")"
. "$scriptsBase/init"

bin="$remapper/build/install/MC-Remapper/bin"
jar="$forgeflower/Server-${VERSION}.jar"

(
	cd "$remapper"
	./gradlew installDist
	
	cd "$bin"
	delete "$forgeflower" "mkdir"
	./MC-Remapper server ${VERSION} --output $jar --fixlocalvar=rename --thread 12
) || exit 1