#!/usr/bin/env bash

# get scripts Base regardless of execution location
SOURCE="${BASH_SOURCE[0]}"
while [ -h "$SOURCE" ]; do # resolve $SOURCE until the file is no longer a symlink
    DIR="$( cd -P "$( dirname "$SOURCE" )" && pwd )"
    SOURCE="$(readlink "$SOURCE")"
    [[ $SOURCE != /* ]] && SOURCE="$DIR/$SOURCE" # if $SOURCE was a relative symlink, we need to resolve it relative to the path where the symlink file was located
done
scriptsBase="$(dirname "$SOURCE")"
. "$scriptsBase/init"

jar="$quiltFlower/Server-${VERSION}.jar"
# shellcheck disable=SC2125
remapperURL=https://search.maven.org/remotecontent?filepath=io/github/lxgaming/reconstruct-cli/1.3.18/reconstruct-cli-1.3.18.jar
serverURL=https://launcher.mojang.com/v1/objects/125e5adf40c659fd3bce3e66e67a16bb49ecc1b9/server.jar
mappingsURL=https://launcher.mojang.com/v1/objects/9717df2acd926bd4a9a7b2ce5f981bb7e4f7f04a/server.txt

(
	cd "$remapper"
	delete "$quiltFlower" "mkdir"

	curl -o server.jar $serverURL
	wget -cO - "$remapperURL" > remapper.jar
	wget -cO - $mappingsURL > mojang_mappings.txt

	java -jar remapper.jar -jar server.jar -mapping mojang_mappings.txt -output remapped-server.jar
	mv remapped-server.jar "$jar"
) || exit 1